version: '3.8'

services:
  app:
    container_name: cdc-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: dev.dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./sql:/app/sql
      - ./src:/app/src
      - ./static:/app/static
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./svelte.config.ts:/app/svelte.config.ts
      - ./tailwind.config.cjs:/app/tailwind.config.cjs
      - ./postcss.config.cjs:/app/postcss.config.cjs
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - 5173:5173
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: cdc-db
    image: postgres:15-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    ports:
      - 5432:5432
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.volumes/dev/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
