export const AUTH_REDIRECT_ACTION_QUERY_PARAM = 'REDIRECT_ACTION';

export enum AuthRedirectAction {}
// CREATE_MOVIE = 'CREATE_MOVIE',

export const AUTH_REDIRECT_ACTION_NAVIGATE_DEFAULT_PAGE = '/';
export const AUTH_REDIRECT_ACTION_NAVIGATE_FOR_NEW_USER = '/';
